version: 0.2
phases:
 install:
   commands:
     - sudo curl -s https://getcomposer.org/installer | php
     - sudo mv  composer.phar /usr/local/bin/composer
     - sudo chmod +x /usr/local/bin/composer
     - sudo cd /usr/local/bin/
     - sudo ./composer
     - php --version


 build:
   commands:
     - echo Build started on `date`
     - echo Installing composer deps
   
     - php artisan cache:clear

 post_build:
   commands:
     - echo Build completed on `date`
    
artifacts:
  type: zip
  files:
    - '**/*'
  name: clyde-$(date +%Y-%m-%d) 
